---
name: Gay Date Checklist
author1: Pando
repo: "https://github.com/casecadet/gay-date-checklist-web"
url1: "https://github.com/casecadet/"
author2: Cryptic
url2: "https://linktr.ee/CrypticFirecat"
